# Numpy Basics
Numpy makes vector and matrix generations very easy.

In [2]:
import numpy as np # import numpy package

## Generating Numpy Array

In [3]:
x = np.array([2.0,5.0,7.0])

In [4]:
print(x)

[ 2.  5.  7.]


In [5]:
type(x)

numpy.ndarray

## Numpy Calculations

In [6]:
x = np.array([2.0,5.0,7.0])

In [7]:
y = np.array([4.0,7.0,10.0])

In [8]:
x + y # vector addition

array([  6.,  12.,  17.])

In [9]:
x - y # vector subtraction

array([-2., -2., -3.])

In [10]:
x * y # element wise product

array([  8.,  35.,  70.])

In [11]:
x / y # element wise division

array([ 0.5       ,  0.71428571,  0.7       ])

## Numpy N-dimension matrix

In [16]:
A = np.array([[2,4],[3,5]])

In [17]:
print(A)

[[2 4]
 [3 5]]


In [18]:
A.shape

(2, 2)

In [19]:
A.dtype # type of elements

dtype('int64')

In [27]:
B = np.matrix([[3,0],[0,6]]) # create another 2x2 matrix

In [28]:
A + B # matrix addition

matrix([[ 5,  4],
        [ 3, 11]])

In [29]:
A * B # matrix element wise multiplication

matrix([[ 6, 24],
        [ 9, 30]])

In [30]:
A * 10 # matrix multiplication by a scalar

array([[20, 40],
       [30, 50]])

## Broadcasting
Broadcasting allows you to calculate matrices with different dimensions. Numpy smartly figures out how different matrix dimensions can be handled altogether.

In [33]:
A = np.array([[1,4],[5,6]])

In [34]:
B = np.array([2,3])

In [35]:
A * B

array([[ 2, 12],
       [10, 18]])

## Accessing matrix elements

In [48]:
X = np.array([[1,5],[2,4],[3,6]])

In [49]:
print(X)

[[1 5]
 [2 4]
 [3 6]]


In [50]:
print(X[0])

[1 5]


In [51]:
print(X[0][1])

5


In [52]:
for row in X:
    print(row)

[1 5]
[2 4]
[3 6]


In [53]:
X = X.flatten() # convert X into a 1D matrix

In [54]:
print(X)

[1 5 2 4 3 6]


In [55]:
X[np.array([2,3])] # obtain 3rd and 4th elements from X

array([2, 4])

In [56]:
X > 2

array([False,  True, False,  True,  True,  True], dtype=bool)

In [58]:
X[X > 2] # get elements larger than 2

array([5, 4, 3, 6])

## Inner Product

In [60]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])

In [61]:
A.shape, B.shape

((2, 3), (3, 2))

In [62]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])